# Generated by Django 4.1.6 on 2023-02-11 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('current_price', models.PositiveIntegerField()),
                ('old_price', models.PositiveIntegerField(default=0)),
                ('price_diff', models.IntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 11, 12, 55, 39, 891190), null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('price_diff', '-created'),
            },
        ),
    ]
