# Generated by Django 4.1.6 on 2023-02-11 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 11, 12, 57, 50, 596164), null=True),
        ),
    ]
